### ISSUE TITLE
Error while locally testing the model : "ModuleNotFoundError: No module named 'ersilia.io.types.text' "

### ISSUE THREAD

**Issue by Femme-js** [ersilia-os/eos1086#3]
[my.log](https://github.com/ersilia-os/eos1086/files/10752972/my.log)

Hi @GemmaTuron and @miquelduranfrigola !

While testing this model locally using the --repo_path command, I am getting this following error. The same error is given by checks too. I have been checking around this error but couldn't get somewhere. I would be needing some help here.

**Comment by GemmaTuron** [comment]
Hi  @Femme-js 

For the sake of checking the models status and making sure we use the testing pipelines appropriately, please do not make a PR if the model is not working locally, ofc it won't work either in the tests.

**Comment by Femme-js** [comment]
Yes @GemmaTuron ! I had a confusion before about the testing the model locally. I did not used to fetch it with ersilia --repo_path command and used to test the code generally. 

I understand it completely now. 

Moreover, the issue has been looked over and we need a text.py inside 'io' folder. 

I have opened the following issue for this. #603
