### ISSUE TITLE
Clean UP & Dockerization eos1086

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos1086#4]

**Comment by GemmaTuron** [comment]
Sorry @emmakodes looks like this model is not done. I'll unassign you
@miquelduranfrigola can you confirm the status?

**Comment by miquelduranfrigola** [comment]
It is on hold until we have a robust Input Adapter for biomedical text. Let's deprioritize it

**Comment by GemmaTuron** [comment]
I'll close this issue, the model will remain a To-Do like eos5ecc until we have a IO for text
